# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html
-keep class com.google.android.libraries.launcherclient.** { *; }
-keep class ua.itaysonlab.hfsdk.** { *; }
-keep class com.google.android.libraries.gsa.d.a.** { *; }

-keep class com.saulhdev.feeder.manager.service.OverlayService.**{*;}

# For Okio
# Animal Sniffer compileOnly dependency to ensure APIs are compatible with older versions of Java.
-dontwarn org.codehaus.mojo.animal_sniffer.*

# For TagSoup
-keep class org.ccil.cowan.tagsoup.** { *; }

# For Jsoup
-keep class org.jsoup.**  { *; }

# For Rome
-keep class com.rometools.** { *; }
-keep class com.rometools.rome.** { *; }
-keep class com.rometools.rome.feed.synd.impl.ConverterForAtom10 { *; }
-keep class com.rometools.rome.feed.synd.SyndFeedImpl { *; }

## Autogenerated in missing_rules.txt deep in build folder
-dontwarn com.android.org.conscrypt.SSLParametersImpl
-dontwarn org.apache.harmony.xnet.provider.jsse.SSLParametersImpl
-dontwarn org.bouncycastle.jsse.BCSSLParameters
-dontwarn org.bouncycastle.jsse.BCSSLSocket
-dontwarn org.bouncycastle.jsse.provider.BouncyCastleJsseProvider
-dontwarn org.openjsse.javax.net.ssl.SSLParameters
-dontwarn org.openjsse.javax.net.ssl.SSLSocket
-dontwarn org.openjsse.net.ssl.OpenJSSE
-dontwarn org.slf4j.impl.StaticLoggerBinder

# ===== kotlinx.serialization =====
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.AnnotationsKt

-keepclassmembers class kotlinx.serialization.json.** {
    *** Companion;
}
-keepclasseswithmembers class kotlinx.serialization.json.** {
    kotlinx.serialization.KSerializer serializer(...);
}

# Keep all @Serializable data classes and their serializers
-keep,includedescriptorclasses class com.saulhdev.feeder.plugins.models.**$$serializer { *; }
-keepclassmembers class com.saulhdev.feeder.plugins.models.** {
    *** Companion;
    *** serializer(...);
    kotlinx.serialization.KSerializer serializer(...);
}
-keepclasseswithmembers class com.saulhdev.feeder.plugins.models.** {
    kotlinx.serialization.KSerializer serializer(...);
}

# Keep the sealed class hierarchy and models
-keep class com.saulhdev.feeder.plugins.models.HubCardData { *; }
-keep class com.saulhdev.feeder.plugins.models.HubCardData$* { *; }
-keep class com.saulhdev.feeder.plugins.models.HubChip { *; }
-keep class com.saulhdev.feeder.plugins.models.HubTimelineItem { *; }
-keep class com.saulhdev.feeder.plugins.models.HubAction { *; }
-keep class com.saulhdev.feeder.plugins.CatalogModule { *; }
-keep class com.saulhdev.feeder.plugins.PluginConfigField { *; }

# ===== Moshi Reflection / JSON Feed (P1-08) =====
-keep class com.saulhdev.feeder.data.entity.** { *; }

# ===== kotlinx.serialization for data.entity (P1-09) =====
-keep,includedescriptorclasses class com.saulhdev.feeder.data.entity.**$$serializer { *; }
-keepclassmembers class com.saulhdev.feeder.data.entity.** {
    *** Companion;
    *** serializer(...);
    kotlinx.serialization.KSerializer serializer(...);
}
-keepclasseswithmembers class com.saulhdev.feeder.data.entity.** {
    kotlinx.serialization.KSerializer serializer(...);
}